name: Deploy website on push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.businessmadebetter.com.au
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /staff.businessmadebetter.com.au/nodeapp/
          local-dir: ./
          port: 21  

      - name: Cache Clean
        run: npm cache clean --force
        
      - name: Run pm2 commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /staff.businessmadebetter.com.au/nodeapp/
            npm install
            pm2 stop app || true
            pm2 start app.js --name app
            pm2 save
          EOF
